# Generated by Django 4.0.6 on 2022-07-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_options_alter_userexam_questions'),
        ('exam', '0004_userexam_is_finished'),
    ]

    operations = [
    ]
